config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :albums

  root 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :tracks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    #code
    @albums = Album.all
  end
  def show
    #code
    @albums = Album.find(params[:id])
    @tracks = @albums.tracks
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<div class="row">
  <%= @albums.each do |a| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag(a.cover)), album_path(a) %>
        <div class="caption">
          <h3 class="title"> <%= a.title %> </h3>
          <p class="artist"> <%= a.artist %> </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/albums/show.html.erb
<div class="show row">
  <div class="cover col-md-4"> <%= image_tag @albums.cover %> </div>
  <div class="col-sm-8">
    <h3 class="album-title"> <%= @albums.title%> </h3>
    <p class="album-artist"> <%= @albums.artist %> </p>
    <%= @tracks.each do |t| %>
    <div class="track row">
      <div class="name col-md-8"> <%= t.name %> </div>
      <div class="minutes col-md-4"> <%= t.minutes %> min</div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BassMusic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css"> -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img class="logo" src="http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/logo.svg"/>
      </div>
    </div>

    <div class="main">
      <div class="container">

        <%= yield %>

      </div>
    </div>

    <div class="footer">
      <div class="container">
        <div class="col-md-2">
          <h3>Bass</h3>
          <ul>
            <li><a href="#">Install</a></li>
            <li><a href="#">Mobile</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>About</h3>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Team</a></li>
            <li><a href="#">Jobs</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>Support</h3>
            <li><a href="#">Help Center</a></li>
            <li><a href="#">Get Started</a></li>
            <li><a href="#">Contact Us</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>Community</h3>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Google+</a></li>
          </ul>
        </div>
      </div>
    </div>

  </body>
</html>